function [dzdt, dfdz, dfdp] = simplebikeV(z,u,p)
%simple bicycle model (suggested to use velocity as an input)

 dzdt=[u(2)*cos(z(3));...
       u(2)*sin(z(3));...
 p(1)*u(1)+p(2)*u(2)+p(3)*u(1)*u(2)];
       
dfdz =[ 0, 0, -u(2)*sin(z(3));...
 0, 0,  u(2)*cos(z(3));...
 0, 0,          0];

dfdp =[  0,     0,  0;...
  0,     0,  0;...
 u(1), u(2),u(1)*u(2)];

end

