function [dzdt,dfdz,dfdp] = lygerosMagic(z,u,p)
%model from lygeros paper with full tire model
%states
x=z(1);
y=z(2);
psi=z(3);
vy=z(4);
w=z(5);

%inputs
d=u(1);
vx=u(2);

%parameters
%p = [m,Iz,lf,l,Bf,Cf,Df]';
scale=[1,.1,.1,.1,1,.1,100];
m=p(1)*scale(1); %mass
Iz=p(2)*scale(2); %moment of inertia
lf=p(3)*scale(3); %length of center of mass from front
l=p(4)*scale(4); %length of wheelbase
Bf=p(5)*scale(5); %front tire coefficient 1
Cf=p(6)*scale(6);%front tire coefficient 2
Df=p(7)*scale(7);%front tire coefficient 3


dzdt=[vx*cos(psi) - vy*sin(psi);...
                                                                                                                                                 vy*cos(psi) + vx*sin(psi);...
                                                                                                                                                                         w;...
 Df*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz) - Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz) - vx*w;...
                                                   (Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf) + Df*lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/Iz];
                                               
                                                   
dfdz=[ 0, 0, - vy*cos(psi) - vx*sin(psi),                                                                                                                                                                                                                                                                                                                              -sin(psi),                                                                                                                                                                                                                                                                                                                                                 0;...
 0, 0,   vx*cos(psi) - vy*sin(psi),                                                                                                                                                                                                                                                                                                                               cos(psi),                                                                                                                                                                                                                                                                                                                                                 0;...
 0, 0,                           0,                                                                                                                                                                                                                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                 1;...
 0, 0,                           0, - (Bf*Cf*Df*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz))/(vx*((vy - (l*w)/2)^2/vx^2 + 1)*(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1)) - (Bf*Cf*Df*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz))/(vx*((vy + (l*w)/2)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1)), (Bf*Cf*Df*l*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz))/(2*vx*((vy - (l*w)/2)^2/vx^2 + 1)*(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1)) - vx - (Bf*Cf*Df*l*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz))/(2*vx*((vy + (l*w)/2)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1));...
 0, 0,                           0,                                              ((Bf*Cf*Df*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf))/(vx*((vy - (l*w)/2)^2/vx^2 + 1)*(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1)) - (Bf*Cf*Df*lf*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/(vx*((vy + (l*w)/2)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1)))/Iz,                                                -((Bf*Cf*Df*l*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf))/(2*vx*((vy - (l*w)/2)^2/vx^2 + 1)*(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1)) + (Bf*Cf*Df*l*lf*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/(2*vx*((vy + (l*w)/2)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1)))/Iz];
 
 


dfdp=[                                                                                                                  0,                                                                                                                                                      0,                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                          0,                                                                                                                                                            0;...
                                                                                                                0,                                                                                                                                                      0,                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                          0,                                                                                                                                                            0;...
                                                                                                                 0,                                                                                                                                                      0,                                                                                                                                                0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0,                                                                                                                                                                                                                                                                                                                  0,                                                                                                                                                                                                                                          0,                                                                                                                                                            0;...
 (Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx))))/m^2 - (Df*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/m^2, (Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf)*(l/2 - lf))/Iz^2 + (Df*lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(l/2 - lf))/Iz^2, (Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(3*l - 4*lf))/(2*Iz) - (Df*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(l - 4*lf))/(2*Iz), (Bf*Cf*Df*w*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz))/(2*vx*((vy - (l*w)/2)^2/vx^2 + 1)*(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1)) - (Df*lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/(2*Iz) - Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*((l - lf)/(2*Iz) + (l/2 - lf)/Iz) - (Bf*Cf*Df*w*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz))/(2*vx*((vy + (l*w)/2)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1)), (Cf*Df*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz)*(d - atan((vy + (l*w)/2)/vx)))/(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1) - (Cf*Df*atan((vy - (l*w)/2)/vx)*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz))/(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1), Df*cos(d)*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz) - Df*atan(Bf*atan((vy - (l*w)/2)/vx))*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz), cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(1/m - (lf*(l/2 - lf))/Iz) - sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(1/m + ((l - lf)*(l/2 - lf))/Iz);...
                                                                                                                  0,                             -(Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf) + Df*lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/Iz^2,                                      -(Df*(sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx))) - cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))))/Iz,                                                                                                                                                    -((Bf*Cf*Df*w*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf))/(2*vx*((vy - (l*w)/2)^2/vx^2 + 1)*(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1)) - Df*sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx))) + (Bf*Cf*Df*lf*w*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/(2*vx*((vy + (l*w)/2)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1)))/Iz,                                            ((Cf*Df*atan((vy - (l*w)/2)/vx)*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf))/(Bf^2*atan((vy - (l*w)/2)/vx)^2 + 1) + (Cf*Df*lf*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx))))*(d - atan((vy + (l*w)/2)/vx)))/(Bf^2*(d - atan((vy + (l*w)/2)/vx))^2 + 1))/Iz,                                            (Df*atan(Bf*atan((vy - (l*w)/2)/vx))*cos(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf) + Df*lf*cos(d)*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))*cos(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/Iz,                                            (sin(Cf*atan(Bf*atan((vy - (l*w)/2)/vx)))*(l - lf) + lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + (l*w)/2)/vx)))))/Iz];
%scaling
scale=repmat(scale,5,1);
  dfdp=scale.*dfdp;
end

