function [dzdt,dfdz,dfdp]=lygerostan(z,u,p)
%states
X=z(1);
Y=z(2);
psi=z(3);%heading
vy=z(4);%lateral velocity
w=z(5);%yaw rate

m=p(1); %mass
Iz=p(2)/10; %moment of inertia
lf=p(3)/10; %lf (length of center of gravity from front wheel)
l=p(4)/10;  %wheelbase length
ca=p(5)*10; %cornering stifness
pr=p(6);%scaling factor for rear tire stifness

%input
d=u(1); %steering input
vx=u(2); %longitudal velocity
dzdt= [ vx*cos(psi) - vy*sin(psi);...
                                                                vy*cos(psi) + vx*sin(psi);...
                                                                                        w;...
    -(ca*pr*atan((vy - w*(l - lf))/vx) - ca*cos(d)*(d - atan((vy + lf*w)/vx)) + m*vx*w)/m;...
 (ca*pr*atan((vy - w*(l - lf))/vx)*(l - lf) + ca*lf*cos(d)*(d - atan((vy + lf*w)/vx)))/Iz];
  
dfdz= [ 0, 0, - vy*cos(psi) - vx*sin(psi),                                                                                                -sin(psi),                                                                                                               0;...
 0, 0,   vx*cos(psi) - vy*sin(psi),                                                                                                 cos(psi),                                                                                                               0;...
 0, 0,                           0,                                                                                                        0,                                                                                                               1;...
 0, 0,                           0,             -((ca*pr)/(vx*((vy - w*(l - lf))^2/vx^2 + 1)) + (ca*cos(d))/(vx*((vy + lf*w)^2/vx^2 + 1)))/m, -(m*vx - (ca*pr*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)) + (ca*lf*cos(d))/(vx*((vy + lf*w)^2/vx^2 + 1)))/m;...
 0, 0,                           0, ((ca*pr*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)) - (ca*lf*cos(d))/(vx*((vy + lf*w)^2/vx^2 + 1)))/Iz,   -((ca*pr*(l - lf)^2)/(vx*((vy - w*(l - lf))^2/vx^2 + 1)) + (ca*lf^2*cos(d))/(vx*((vy + lf*w)^2/vx^2 + 1)))/Iz];
 
dfdp=[                                                                                 0,                                                                                           0,                                                                                                                                                                                       0,                                                                                              0,                                                                                  0,                                           0;...
                                                                                 0,                                                                                           0,                                                                                                                                                                                       0,                                                                                              0,                                                                                  0,                                           0;...
                                                                                 0,                                                                                           0,                                                                                                                                                                                       0,                                                                                              0,                                                                                  0,                                           0;...
 (ca*(pr*atan((vy - w*(l - lf))/vx) - d*cos(d) + atan((vy + lf*w)/vx)*cos(d)))/m^2,                                                                                           0,                                                                                        -.1*(((ca*pr*w)/(vx*((vy - w*(l - lf))^2/vx^2 + 1)) + (ca*w*cos(d))/(vx*((vy + lf*w)^2/vx^2 + 1)))/m),                                                .1*((ca*pr*w)/(m*vx*((vy - w*(l - lf))^2/vx^2 + 1))),             -10*(pr*atan((vy - w*(l - lf))/vx) - cos(d)*(d - atan((vy + lf*w)/vx)))/m,          -(ca*atan((vy - w*(l - lf))/vx))/m;...
                                                                                 0, -.1*((ca*pr*atan((vy - w*(l - lf))/vx)*(l - lf) + ca*lf*cos(d)*(d - atan((vy + lf*w)/vx))))/Iz^2, -.1*(((ca*pr*atan((vy - w*(l - lf))/vx) - ca*cos(d)*(d - atan((vy + lf*w)/vx)) - (ca*pr*w*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)) + (ca*lf*w*cos(d))/(vx*((vy + lf*w)^2/vx^2 + 1)))/Iz)), .1*(ca*pr*atan((vy - w*(l - lf))/vx) - (ca*pr*w*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)))/Iz, 10*(pr*atan((vy - w*(l - lf))/vx)*(l - lf) + lf*cos(d)*(d - atan((vy + lf*w)/vx)))/Iz, (ca*atan((vy - w*(l - lf))/vx)*(l - lf))/Iz];
 
end