function [dzdt,dfdz,dfdp] = lygerosMagic(z,u,p)
%model from lygeros paper with full tire model
%states
x=z(1);
y=z(2);
psi=z(3);
vy=z(4);
w=z(5);

%inputs
d=u(1);
vx=u(2);

%parameters
%p = [m,Iz,lf,l,Bf,Cf,Df,prB,prC,prD]';
m=p(1); %mass
Iz=p(2)/10; %moment of inertia
lf=p(3)/10; %length of center of mass from front
l=p(4)/10; %length of wheelbase 
Bf=p(5)*10; %front tire coefficient 1
Cf=p(6);%front tire coefficient 2
Df=p(7);%front tire coefficient 3
prB=p(8);%ratio of rear:front tire coefficeint 1
prC=p(9);%ratio of rear:front tire coefficeint 2
prD=p(10);%ratio of rear:front tire coefficeint 3
p1=p(11);%scaling for steering input
p2=p(12);%scaling for steering input

dzdt=[vx*cos(psi) - vy*sin(psi);...
vy*cos(psi) + vx*sin(psi);...
w;...
Df*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz) - Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz) - vx*w;...
(Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf) + Df*lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/Iz];
 

dfdz=[ 0, 0, - vy*cos(psi) - vx*sin(psi),                                                                                                                                                                                                                                                                                      -sin(psi),                                                                                                                                                                                                                                                                                                         0;...
 0, 0,   vx*cos(psi) - vy*sin(psi),                                                                                                                                                                                                                                                                                       cos(psi),                                                                                                                                                                                                                                                                                                         0;...
 0, 0,                           0,                                                                                                                                                                                                                                                                                              0,                                                                                                                                                                                                                                                                                                         1;...
 0, 0,                           0, - (Bf*Cf*Df*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz))/(vx*(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1)) - (Bf*Cf*Df*prB*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz))/(vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)), (Bf*Cf*Df*l*prB*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz))/(2*vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)) - (Bf*Cf*Df*l*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz))/(2*vx*(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1)) - vx;...
 0, 0,                           0,                                             -((Bf*Cf*Df*lf*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/(vx*(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1)) - (Bf*Cf*Df*prB*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf))/(vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)))/Iz,                                                -((Bf*Cf*Df*l*lf*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/(2*vx*(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1)) + (Bf*Cf*Df*l*prB*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf))/(2*vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)))/Iz];
 
 
dfdp=[                                                                                                                            0,                                                                                                                                                                  0,                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                  0,                                                                                                                                                                      0,                                                                                                                                                              0,                                                                                                                         0,                                                                                 0,                                                                                        0,                                                                                      0;...
                                                                                                                            0,                                                                                                                                                                  0,                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                  0,                                                                                                                                                                      0,                                                                                                                                                              0,                                                                                                                         0,                                                                                 0,                                                                                        0,                                                                                      0;...
                                                                                                                            0,                                                                                                                                                                  0,                                                                                                                                                                        0,                                                                                                                                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                                                                                        0,                                                                                                                                                                                                                                                  0,                                                                                                                                                                      0,                                                                                                                                                              0,                                                                                                                         0,                                                                                 0,                                                                                        0,                                                                                      0;...
 (Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx)))/m^2 - (Df*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/m^2, - (Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf)*(l/2 - lf))/Iz^2 - (Df*lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(l/2 - lf))/Iz^2, - Df*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(lf/Iz - (l/2 - lf)/Iz) - Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*((l - lf)/Iz + (l/2 - lf)/Iz), Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*((l - lf)/(2*Iz) + (l/2 - lf)/Iz) + (Df*lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/(2*Iz) - (Bf*Cf*Df*w*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz))/(2*vx*(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1)) + (Bf*Cf*Df*prB*prC*prD*w*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz))/(2*vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)), (Cf*Df*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(d - (vy + (l*w)/2)/vx)*(1/m + (lf*(l/2 - lf))/Iz))/(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1) - (Cf*Df*prB*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(vy - (l*w)/2)*(1/m - ((l - lf)*(l/2 - lf))/Iz))/(vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)), Df*atan(Bf*(d - (vy + (l*w)/2)/vx))*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz) - Df*prC*prD*atan((Bf*prB*(vy - (l*w)/2))/vx)*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz), sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz) - prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz), -(Bf*Cf*Df*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(vy - (l*w)/2)*(1/m - ((l - lf)*(l/2 - lf))/Iz))/(vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)), -Cf*Df*prD*atan((Bf*prB*(vy - (l*w)/2))/vx)*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz), -Df*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(1/m - ((l - lf)*(l/2 - lf))/Iz), -Df*d*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*sin(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz), -Df*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*sin(p2 + d*p1)*(1/m + (lf*(l/2 - lf))/Iz);...
                                                                                                                            0,                               -(Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf) + Df*lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/Iz^2,                                                    (Df*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1) - Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx)))/Iz,                                                                                                                                                      -((Bf*Cf*Df*lf*w*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/(2*vx*(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1)) - Df*prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx)) + (Bf*Cf*Df*prB*prC*prD*w*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf))/(2*vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)))/Iz,                                            ((Cf*Df*lf*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1)*(d - (vy + (l*w)/2)/vx))/(Bf^2*(d - (vy + (l*w)/2)/vx)^2 + 1) + (Cf*Df*prB*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(vy - (l*w)/2)*(l - lf))/(vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)))/Iz,                                            (Df*lf*atan(Bf*(d - (vy + (l*w)/2)/vx))*cos(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1) + Df*prC*prD*atan((Bf*prB*(vy - (l*w)/2))/vx)*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf))/Iz,                                            (prD*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf) + lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*cos(p2 + d*p1))/Iz,                       (Bf*Cf*Df*prC*prD*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(vy - (l*w)/2)*(l - lf))/(Iz*vx*((Bf^2*prB^2*(vy - (l*w)/2)^2)/vx^2 + 1)),                     (Cf*Df*prD*atan((Bf*prB*(vy - (l*w)/2))/vx)*cos(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf))/Iz,                     (Df*sin(Cf*prC*atan((Bf*prB*(vy - (l*w)/2))/vx))*(l - lf))/Iz,                    -(Df*d*lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*sin(p2 + d*p1))/Iz,                    -(Df*lf*sin(Cf*atan(Bf*(d - (vy + (l*w)/2)/vx)))*sin(p2 + d*p1))/Iz];
 
%add scaling to jacobian for parameters 
m=[1,.1,.1,.1,10,1,1,1,1,1,1,1];
m=repmat(m,5,1);
dfdp=m.*dfdp;



end

