function [dzdt,dfdz,dfdp] = lygerosMagic(z,u,p)
%model from lygeros paper with full tire model
%states
x=z(1);
y=z(2);
psi=z(3);
vy=z(4);
w=z(5);

%inputs
d=u(1);
vx=u(2);

%parameters
%p = [m,Iz,lf,l,Bf,Cf,Df,prB,prC,prD]';
m=p(1); %mass
Iz=p(2)/10; %moment of inertia
lf=p(3)/10; %length of center of mass from front
l=p(4)/10; %length of wheelbase 
Bf=p(5); %front tire coefficient 1
Cf=p(6);%front tire coefficient 2
Df=p(7)*10;%front tire coefficient 3
prB=p(8);%ratio of rear:front tire coefficeint 1
prC=p(9);%ratio of rear:front tire coefficeint 2
prD=p(10);%ratio of rear:front tire coefficeint 3


dzdt=[vx*cos(psi) - vy*sin(psi);...
        vy*cos(psi) + vx*sin(psi);...
            w;...
    -(m*vx*w - Df*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))) + Df*prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/m;...
 (Df*prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf) + Df*lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/Iz];

dfdz=[ 0, 0, - vy*cos(psi) - vx*sin(psi),                                                                                                                                                                                                                                                                                                            -sin(psi),                                                                                                                                                                                                                                                                                                                          0;...
 0, 0,   vx*cos(psi) - vy*sin(psi),                                                                                                                                                                                                                                                                                                             cos(psi),                                                                                                                                                                                                                                                                                                                          0;...
 0, 0,                           0,                                                                                                                                                                                                                                                                                                                    0,                                                                                                                                                                                                                                                                                                                          1;...
 0, 0,                           0,              -((Bf*Cf*Df*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/(vx*((vy + lf*w)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1)) + (Bf*Cf*Df*prB*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/m, -(m*vx + (Bf*Cf*Df*lf*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/(vx*((vy + lf*w)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1)) - (Bf*Cf*Df*prB*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/m;...
 0, 0,                           0, -((Bf*Cf*Df*lf*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/(vx*((vy + lf*w)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1)) - (Bf*Cf*Df*prB*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/Iz,   -((Bf*Cf*Df*lf^2*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/(vx*((vy + lf*w)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1)) + (Bf*Cf*Df*prB*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf)^2)/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/Iz];
 
 
dfdp=[                                                                                                                              0,                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                   0,                                                                                                                             0,                                                                                                                                                             0,                                                                                                                   0,                                                                    0;...
                                                                                                                              0,                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                   0,                                                                                                                             0,                                                                                                                                                             0,                                                                                                                   0,                                                                    0;...
                                                                                                                              0,                                                                                                                                      0,                                                                                                                                                                                                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                         0,                                                                                                                                                                                                                                                                                                 0,                                                                                                                                                                                                                   0,                                                                                                                             0,                                                                                                                                                             0,                                                                                                                   0,                                                                    0;...
 (Df*prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/m^2 - (Df*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/m^2,                                                                                                                                      0,                                                                                                                                  -((Bf*Cf*Df*w*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/(vx*((vy + lf*w)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1)) + (Bf*Cf*Df*prB*prC*prD*w*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/m,                                                                          (Bf*Cf*Df*prB*prC*prD*w*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/(m*vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)),              ((Cf*Df*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx))))*(d - atan((vy + lf*w)/vx)))/(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1) - (Cf*Df*prB*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*atan((vy - w*(l - lf))/vx))/(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1))/m,              (Df*cos(d)*atan(Bf*(d - atan((vy + lf*w)/vx)))*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))) - Df*prC*prD*atan(Bf*prB*atan((vy - w*(l - lf))/vx))*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/m,              (cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))) - prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/m,          -(Bf*Cf*Df*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*atan((vy - w*(l - lf))/vx))/(m*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)),          -(Cf*Df*prD*atan(Bf*prB*atan((vy - w*(l - lf))/vx))*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/m,          -(Df*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))))/m;...
                                                                                                                              0, -(Df*prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf) + Df*lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/Iz^2, (Df*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))) - Df*prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))) - (Bf*Cf*Df*lf*w*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/(vx*((vy + lf*w)^2/vx^2 + 1)*(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1)) + (Bf*Cf*Df*prB*prC*prD*w*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/Iz, (Df*prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx))) - (Bf*Cf*Df*prB*prC*prD*w*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/(vx*((vy - w*(l - lf))^2/vx^2 + 1)*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)))/Iz, ((Cf*Df*lf*cos(d)*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx))))*(d - atan((vy + lf*w)/vx)))/(Bf^2*(d - atan((vy + lf*w)/vx))^2 + 1) + (Cf*Df*prB*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*atan((vy - w*(l - lf))/vx)*(l - lf))/(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1))/Iz, (Df*lf*cos(d)*atan(Bf*(d - atan((vy + lf*w)/vx)))*cos(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))) + Df*prC*prD*atan(Bf*prB*atan((vy - w*(l - lf))/vx))*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/Iz, (prD*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf) + lf*cos(d)*sin(Cf*atan(Bf*(d - atan((vy + lf*w)/vx)))))/Iz, (Bf*Cf*Df*prC*prD*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*atan((vy - w*(l - lf))/vx)*(l - lf))/(Iz*(Bf^2*prB^2*atan((vy - w*(l - lf))/vx)^2 + 1)), (Cf*Df*prD*atan(Bf*prB*atan((vy - w*(l - lf))/vx))*cos(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/Iz, (Df*sin(Cf*prC*atan(Bf*prB*atan((vy - w*(l - lf))/vx)))*(l - lf))/Iz];
%add scaling to jacobian for parameters 
m=[1,.1,.1,1,1,1,10,1,1,1];
m=repmat(m,5,1);
dfdp=m.*dfdp;



end

